/* Master Scanner dashboard
   Compatible with resultdow.json / resultwgat.json generated by
   DOW_JSON.py and WGAT_JSON.py in this repository.
*/

const DATA = { dow: [], wgat: [] };
const SORT = {
  dow: { key: "stock", dir: "asc" },
  wgat: { key: "stock", dir: "asc" }
};
const EXPANDED = { dow: new Set(), wgat: new Set() };

const FIBS = [
  ["23pct", "23%"],
  ["38pct", "38%"],
  ["50pct", "50%"],
  ["618pct", "61.8%"],
  ["78pct", "78%"]
];

const FILES = {
  dow: "resultdow.json",
  wgat: "resultwgat.json"
};

document.addEventListener("DOMContentLoaded", init);

async function init() {
  wireTabs();
  wireFilters();
  wireSorting();

  try {
    const [dowRaw, wgatRaw] = await Promise.all([
      fetchJSON(FILES.dow),
      fetchJSON(FILES.wgat)
    ]);

    DATA.dow = normalizeDow(dowRaw);
    DATA.wgat = normalizeWgat(wgatRaw);

    updateMeta(dowRaw, wgatRaw);
    renderTable("dow");
    renderTable("wgat");
    renderTicker("dow");
  } catch (err) {
    console.error("Scanner data load error:", err);
    showFetchError(err);
  }
}

async function fetchJSON(file) {
  const url = `${file}?v=${Date.now()}`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  return await res.json();
}

/* =========================================================
   DATA NORMALIZATION
   ========================================================= */
function normalizeDow(raw) {
  // New DOW_JSON.py format:
  // { timeframes: { "Daily": { results: [...] }, ... } }
  const rows = [];
  const timeframes = raw?.timeframes || {};

  Object.entries(timeframes).forEach(([tf, block]) => {
    (block?.results || []).forEach(r => {
      rows.push({
        stock: String(r.Stock ?? r.stock ?? ""),
        timeframe: String(r.Timeframe ?? r.timeframe ?? tf),
        trend_bucket: String(r["Trend Bucket"] ?? r.trend_bucket ?? ""),
        last_close: num(r.Close ?? r["Last Close"] ?? r.last_close),
        last_date: r["Scan Date"] ?? r["Last Candle"] ?? r.last_date ?? null,
        "23pct_bull": bool(r["23% Bull"], r["23pct_bull"]),
        "38pct_bull": bool(r["38% Bull"], r["38pct_bull"]),
        "50pct_bull": bool(r["50% Bull"], r["50pct_bull"]),
        "618pct_bull": bool(r["61.8% Bull"], r["618pct_bull"]),
        "78pct_bull": bool(r["78% Bull"], r["78pct_bull"]),
        "23pct_bear": bool(r["23% Bear"], r["23pct_bear"]),
        "38pct_bear": bool(r["38% Bear"], r["38pct_bear"]),
        "50pct_bear": bool(r["50% Bear"], r["50pct_bear"]),
        "618pct_bear": bool(r["61.8% Bear"], r["618pct_bear"]),
        "78pct_bear": bool(r["78% Bear"], r["78pct_bear"]),
        "23pct_up": num(r["23% Up"] ?? r["23pct_up"]),
        "38pct_up": num(r["38% Up"] ?? r["38pct_up"]),
        "50pct_up": num(r["50% Up"] ?? r["50pct_up"]),
        "618pct_up": num(r["61.8% Up"] ?? r["618pct_up"]),
        "78pct_up": num(r["78% Up"] ?? r["78pct_up"]),
        "23pct_down": num(r["23% Down"] ?? r["23pct_down"]),
        "38pct_down": num(r["38% Down"] ?? r["38pct_down"]),
        "50pct_down": num(r["50% Down"] ?? r["50pct_down"]),
        "618pct_down": num(r["61.8% Down"] ?? r["618pct_down"]),
        "78pct_down": num(r["78% Down"] ?? r["78pct_down"])
      });
    });
  });

  return rows;
}

function normalizeWgat(raw) {
  // New WGAT_JSON.py format:
  // { scan: { results: [...] } }
  const source = raw?.scan?.results || raw?.results || [];
  return source.map(r => ({
    stock: String(r.Stock ?? r.stock ?? ""),
    category_1: String(r["Category 1"] ?? r.category_1 ?? "No Clear Trend"),
    last_close: num(r.Close ?? r["Last Close"] ?? r.last_close),
    last_date: r["Scan Date"] ?? r["Last Candle"] ?? r.last_date ?? null,
    daily_macd: r["Daily MACD"] ?? r.daily_macd ?? null,
    previous_daily_macd: r["Previous Daily MACD"] ?? r.previous_daily_macd ?? null,
    weekly_macd: r["Weekly MACD"] ?? r.weekly_macd ?? null,
    monthly_macd: r["Monthly MACD"] ?? r.monthly_macd ?? null,
    bullish_momentum: bool(r["Bullish Momentum"], r.bullish_momentum),
    bearish_momentum: bool(r["Bearish Momentum"], r.bearish_momentum),
    bullish_swing: bool(r["Bullish Swing"], r.bullish_swing),
    bearish_swing: bool(r["Bearish Swing"], r.bearish_swing),
    rsi: num(r.RSI ?? r.rsi),
    adx: num(r.ADX ?? r.adx)
  }));
}

function bool(...values) {
  for (const v of values) if (v !== undefined && v !== null) return v === true || v === 1 || v === "true";
  return false;
}

function num(v) {
  if (v === undefined || v === null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

/* =========================================================
   META / ERROR
   ========================================================= */
function updateMeta(dow, wgat) {
  document.getElementById("metaLive").textContent = "data loaded";
  const genAt = dow?.generated_at || wgat?.generated_at;
  const scanDate =
    dow?.scan_date ||
    wgat?.scan?.scan_date ||
    Object.values(dow?.timeframes || {}).find(x => x?.scan_date)?.scan_date ||
    "—";

  document.getElementById("metaDate").textContent =
    `Scan date: ${formatDate(scanDate)} · generated ${genAt ? new Date(genAt).toLocaleString() : "—"}`;
}

function showFetchError(err) {
  const message = `
    <div class="icon">⚠</div>
    <h3>Couldn't load scan data</h3>
    <p>The dashboard could not load <code>resultdow.json</code> and/or <code>resultwgat.json</code>.</p>
    <p class="error-detail"><code>${escapeHTML(err.message || String(err))}</code></p>
    <p>Both files must be in the same <code>wgat/</code> folder as <code>index.html</code>.</p>
    <button class="btn primary" onclick="location.reload()">Reload Data</button>
  `;
  ["dowState", "wgatState"].forEach(id => {
    const el = document.getElementById(id);
    el.innerHTML = message;
    el.classList.remove("hidden");
  });
  document.getElementById("metaLive").textContent = "no data";
}

/* =========================================================
   TABS
   ========================================================= */
function wireTabs() {
  document.querySelectorAll(".tab-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tab-btn").forEach(b => {
        b.classList.remove("active");
        b.setAttribute("aria-selected", "false");
      });
      btn.classList.add("active");
      btn.setAttribute("aria-selected", "true");
      const tab = btn.dataset.tab;
      document.querySelectorAll(".tab-panel").forEach(p => p.classList.add("hidden"));
      document.getElementById(`tab-${tab}`).classList.remove("hidden");
      renderTicker(tab);
    });
  });
}

/* =========================================================
   FILTERS
   ========================================================= */
function wireFilters() {
  ["dowTimeframe", "dowTrend", "dowFib", "dowSearch"].forEach(id => {
    document.getElementById(id).addEventListener("input", () => {
      renderTable("dow");
      renderTicker("dow");
    });
  });

  document.getElementById("dowReset").addEventListener("click", () => {
    document.getElementById("dowTimeframe").value = "Daily";
    document.getElementById("dowTrend").value = "All";
    document.getElementById("dowFib").value = "All";
    document.getElementById("dowSearch").value = "";
    renderTable("dow"); renderTicker("dow");
  });

  ["wgatCat1", "wgatCat2", "wgatSearch"].forEach(id => {
    document.getElementById(id).addEventListener("input", () => {
      renderTable("wgat");
      renderTicker("wgat");
    });
  });

  document.getElementById("wgatReset").addEventListener("click", () => {
    document.getElementById("wgatCat1").value = "All";
    document.getElementById("wgatCat2").value = "All";
    document.getElementById("wgatSearch").value = "";
    renderTable("wgat"); renderTicker("wgat");
  });
}

function getDowFiltered() {
  const tf = document.getElementById("dowTimeframe").value;
  const trend = document.getElementById("dowTrend").value;
  const fib = document.getElementById("dowFib").value;
  const q = document.getElementById("dowSearch").value.trim().toUpperCase();

  return DATA.dow.filter(r => {
    if (tf !== "All" && r.timeframe !== tf) return false;
    if (trend !== "All" && r.trend_bucket !== trend) return false;
    if (fib !== "All" && r[fib] !== true) return false;
    if (q && !r.stock.toUpperCase().includes(q)) return false;
    return true;
  });
}

function getWgatFiltered() {
  const cat1 = document.getElementById("wgatCat1").value;
  const cat2 = document.getElementById("wgatCat2").value;
  const q = document.getElementById("wgatSearch").value.trim().toUpperCase();

  return DATA.wgat.filter(r => {
    if (cat1 !== "All" && r.category_1 !== cat1) return false;
    if (cat2 !== "All" && r[cat2] !== true) return false;
    if (q && !r.stock.toUpperCase().includes(q)) return false;
    return true;
  });
}

/* =========================================================
   SORTING
   ========================================================= */
function wireSorting() {
  document.querySelectorAll("#dowTable th.sortable").forEach(th => th.addEventListener("click", () => toggleSort("dow", th)));
  document.querySelectorAll("#wgatTable th.sortable").forEach(th => th.addEventListener("click", () => toggleSort("wgat", th)));
}

function toggleSort(scope, th) {
  const key = th.dataset.key;
  const s = SORT[scope];
  if (s.key === key) s.dir = s.dir === "asc" ? "desc" : "asc";
  else { s.key = key; s.dir = "asc"; }
  renderTable(scope);
}

function applySort(rows, scope) {
  const { key, dir } = SORT[scope];
  const mult = dir === "asc" ? 1 : -1;
  return [...rows].sort((a, b) => {
    const av = a[key], bv = b[key];
    if (av == null && bv == null) return 0;
    if (av == null) return 1;
    if (bv == null) return -1;
    if (typeof av === "string") return av.localeCompare(String(bv)) * mult;
    return (av - bv) * mult;
  });
}

function updateSortHeaders(tableId, scope) {
  document.querySelectorAll(`#${tableId} th.sortable`).forEach(th => {
    th.classList.remove("sorted-asc", "sorted-desc");
    if (th.dataset.key === SORT[scope].key) {
      th.classList.add(SORT[scope].dir === "asc" ? "sorted-asc" : "sorted-desc");
    }
  });
}

/* =========================================================
   DOW TABLE
   ========================================================= */
function renderDow() {
  const body = document.getElementById("dowBody");
  const state = document.getElementById("dowState");
  body.innerHTML = "";

  let rows = applySort(getDowFiltered(), "dow");
  updateSortHeaders("dowTable", "dow");
  document.getElementById("dowCount").innerHTML = `<b>${rows.length}</b> rows`;

  if (!rows.length) {
    state.classList.remove("hidden");
    state.innerHTML = emptyState("No stocks match these filters", "Try All Timeframes or widen the trend filter.");
    return;
  }
  state.classList.add("hidden");

  const frag = document.createDocumentFragment();
  rows.forEach(r => {
    const id = `${r.stock}__${r.timeframe}`;
    const tr = document.createElement("tr");
    if (EXPANDED.dow.has(id)) tr.classList.add("expanded");
    tr.innerHTML = `
      <td><div class="cell-stock"><span class="stock-ticker">${escapeHTML(r.stock)}</span></div></td>
      <td><span class="tf-tag">${escapeHTML(r.timeframe)}</span></td>
      <td><span class="badge ${trendBadgeClass(r.trend_bucket)}"><span class="stamp">${abbrevTrend(r.trend_bucket)}</span> ${escapeHTML(r.trend_bucket)}</span></td>
      <td class="mono strong">${fmtNum(r.last_close)}</td>
      <td>${fibChips(r, "bull")}</td>
      <td>${fibChips(r, "bear")}</td>
      <td class="mono">${formatDate(r.last_date)}</td>
    `;
    tr.addEventListener("click", () => toggleExpand("dow", id));
    frag.appendChild(tr);
    if (EXPANDED.dow.has(id)) frag.appendChild(buildDowExpand(r));
  });
  body.appendChild(frag);
}

function buildDowExpand(r) {
  const tr = document.createElement("tr");
  tr.className = "expand-row";
  const td = document.createElement("td");
  td.colSpan = 7;
  td.innerHTML = `
    <div class="expand-inner">
      <div class="expand-col">
        <h4>Fib Retracement Levels</h4>
        <div class="kv-list">${FIBS.map(([k,l]) => `<div class="kv-row"><span>${l}</span><span>${r[`${k}_up`] != null ? "↑ " + fmtNum(r[`${k}_up`]) : r[`${k}_down`] != null ? "↓ " + fmtNum(r[`${k}_down`]) : "—"}</span></div>`).join("")}</div>
      </div>
      <div class="expand-col">
        <h4>Detail</h4>
        <div class="kv-list">
          <div class="kv-row"><span>Stock</span><span>${escapeHTML(r.stock)}</span></div>
          <div class="kv-row"><span>Timeframe</span><span>${escapeHTML(r.timeframe)}</span></div>
          <div class="kv-row"><span>Trend</span><span>${escapeHTML(r.trend_bucket)}</span></div>
          <div class="kv-row"><span>Close</span><span>${fmtNum(r.last_close)}</span></div>
          <div class="kv-row"><span>Candle</span><span>${formatDate(r.last_date)}</span></div>
        </div>
      </div>
    </div>`;
  tr.appendChild(td);
  return tr;
}

/* =========================================================
   WGAT TABLE
   ========================================================= */
function renderWgat() {
  const body = document.getElementById("wgatBody");
  const state = document.getElementById("wgatState");
  body.innerHTML = "";

  let rows = applySort(getWgatFiltered(), "wgat");
  updateSortHeaders("wgatTable", "wgat");
  document.getElementById("wgatCount").innerHTML = `<b>${rows.length}</b> rows`;

  if (!rows.length) {
    state.classList.remove("hidden");
    state.innerHTML = emptyState("No stocks match these filters", "Try All or remove the stock search.");
    return;
  }
  state.classList.add("hidden");

  const frag = document.createDocumentFragment();
  rows.forEach(r => {
    const id = r.stock;
    const tr = document.createElement("tr");
    if (EXPANDED.wgat.has(id)) tr.classList.add("expanded");
    tr.innerHTML = `
      <td><div class="cell-stock"><span class="stock-ticker">${escapeHTML(r.stock)}</span></div></td>
      <td><span class="badge ${wgatBadgeClass(r.category_1)}">${escapeHTML(r.category_1)}</span></td>
      <td>${signalChips(r)}</td>
      <td class="mono strong">${fmtNum(r.last_close)}</td>
      <td class="mono">${fmtNum(r.rsi, 1)}</td>
      <td class="mono">${fmtNum(r.adx, 1)}</td>
      <td class="mono">${formatDate(r.last_date)}</td>
    `;
    tr.addEventListener("click", () => toggleExpand("wgat", id));
    frag.appendChild(tr);
    if (EXPANDED.wgat.has(id)) frag.appendChild(buildWgatExpand(r));
  });
  body.appendChild(frag);
}

function buildWgatExpand(r) {
  const tr = document.createElement("tr");
  tr.className = "expand-row";
  const td = document.createElement("td");
  td.colSpan = 7;
  td.innerHTML = `
    <div class="expand-inner">
      <div class="expand-col">
        <h4>Wave vs Tide</h4>
        <div class="kv-list">
          <div class="kv-row"><span>Daily MACD</span><span>${escapeHTML(r.daily_macd ?? "—")}</span></div>
          <div class="kv-row"><span>Previous Daily</span><span>${escapeHTML(r.previous_daily_macd ?? "—")}</span></div>
          <div class="kv-row"><span>Weekly MACD</span><span>${escapeHTML(r.weekly_macd ?? "—")}</span></div>
          <div class="kv-row"><span>Monthly MACD</span><span>${escapeHTML(r.monthly_macd ?? "—")}</span></div>
        </div>
      </div>
      <div class="expand-col">
        <h4>Indicators</h4>
        <div class="kv-list">
          <div class="kv-row"><span>RSI</span><span>${fmtNum(r.rsi, 2)}</span></div>
          <div class="kv-row"><span>ADX</span><span>${fmtNum(r.adx, 2)}</span></div>
          <div class="kv-row"><span>Close</span><span>${fmtNum(r.last_close)}</span></div>
          <div class="kv-row"><span>Candle</span><span>${formatDate(r.last_date)}</span></div>
        </div>
      </div>
    </div>`;
  tr.appendChild(td);
  return tr;
}

function signalChips(r) {
  const items = [
    [r.bullish_momentum, "BM", "bull"],
    [r.bearish_momentum, "BRM", "bear"],
    [r.bullish_swing, "BS", "bull"],
    [r.bearish_swing, "BRS", "bear"]
  ];
  return `<div class="chipset">${items.map(([on,label,side]) => `<span class="signal-dot ${on ? `on ${side}` : ""}" title="${label}"></span>`).join("")}</div>`;
}

function toggleExpand(scope, id) {
  if (EXPANDED[scope].has(id)) EXPANDED[scope].delete(id);
  else EXPANDED[scope].add(id);
  renderTable(scope);
}

/* =========================================================
   TICKER
   ========================================================= */
function renderTicker(scope) {
  const track = document.getElementById("tickerTrack");
  if (!track) return;
  const rows = scope === "dow" ? getDowFiltered() : getWgatFiltered();
  const items = rows.slice(0, 40).map(r => {
    const label = scope === "dow" ? r.stock : r.stock;
    const value = scope === "dow" ? r.trend_bucket : r.category_1;
    const cls = scope === "dow" ? trendBadgeClass(r.trend_bucket) : wgatBadgeClass(r.category_1);
    return `<span class="ticker-chip ${cls}"><span class="lbl">${escapeHTML(label)}</span><span class="val">${escapeHTML(value)}</span></span>`;
  });
  const html = items.length ? items.join("") : `<span class="ticker-chip neutral"><span class="lbl">Scanner</span><span class="val">No matching rows</span></span>`;
  track.innerHTML = html + html;
}

/* =========================================================
   HELPERS
   ========================================================= */
function renderTable(scope) {
  if (scope === "dow") renderDow();
  else renderWgat();
}

function trendBadgeClass(bucket = "") {
  if (bucket === "Uptrend" || bucket === "Reversal To Uptrend") return "bull";
  if (bucket === "Downtrend" || bucket === "Reversal To Downtrend") return "bear";
  return "neutral";
}

function wgatBadgeClass(cat = "") {
  if (cat.includes("Uptrend") || cat.includes("Aligned Up") || cat.includes("Going Up")) return "bull";
  if (cat.includes("Down") || cat.includes("Aligned Down")) return "bear";
  return "neutral";
}

function abbrevTrend(bucket) {
  const map = { "Uptrend":"UP", "Downtrend":"DN", "Reversal To Uptrend":"REV↑", "Reversal To Downtrend":"REV↓", "Triangle / Sideways":"SIDE" };
  return map[bucket] || "—";
}

function fibChips(r, side) {
  return `<div class="chipset">${FIBS.map(([k,l]) => {
    const on = r[`${k}_${side}`] === true;
    const price = r[`${k}_${side === "bull" ? "up" : "down"}`];
    return `<span class="chip-dot ${on ? `on ${side}` : ""}" title="${l} ${side} ${price != null ? "@ " + fmtNum(price) : "—"}">${l}</span>`;
  }).join("")}</div>`;
}

function fmtNum(v, decimals = 2) {
  if (v == null || !Number.isFinite(Number(v))) return "—";
  return Number(v).toLocaleString("en-IN", { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
}

function formatDate(v) {
  if (!v) return "—";
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleDateString("en-IN", { year:"numeric", month:"short", day:"2-digit" });
}

function emptyState(title, sub) {
  return `<div class="icon">⌁</div><h3>${escapeHTML(title)}</h3><p>${escapeHTML(sub)}</p>`;
}

function loadingState() { return `<div class="icon">…</div><h3>Loading scan data</h3><p>Please wait.</p>`; }

function escapeHTML(value) {
  return String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
}
